### ISSUE TITLE
How to fix the issue of Data Loader does not work with Hdf5 file

### ISSUE THREAD

**Issue by bozliu** [ychfan/wdsr#4]
Error Log:

Traceback (most recent call last):
  File "trainer.py", line 272, in <module>
    train(epoch)
  File "trainer.py", line 216, in train
    for batch_idx, (data, target) in enumerate(train_data_loader):
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 989, in _next_data
    return self._process_data(data)
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lbz/ACV/wdsr/datasets/_isr.py", line 66, in __getitem__
    lr_image, hr_image = self._load_item(index)
  File "/home/lbz/ACV/wdsr/datasets/_isr.py", line 159, in _load_item
    lr_image = self.lr_cache_file.get(self.lr_files[index][0])
  File "/home/lbz/ACV/wdsr/common/io.py", line 50, in get
    return self.file[key]
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/home/lbz/anaconda3/envs/ACV/lib/python3.7/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object '0362.png' doesn't exist)"

**Comment by ychfan** [comment]
You may need to delete the `./cache` folder in the code directory.

**Comment by bozliu** [comment]
Thank you for your reply. I understand that you want me to re-generate Hdf5 again. However, the same error shows again.

**Comment by bozliu** [comment]
Firstly, I thought there is a problem caused by Data Loader does not work with Hdf5 file, when num_worker >1 from the referred link, [https://discuss.pytorch.org/t/dataloader-when-num-worker-0-there-is-bug/25643/8](ur) and [https://github.com/pytorch/pytorch/issues/11929](url).
However, this code can run well on Colab and therefore I believe there is a library problem of Hdf5 on the server. 

The procedure to solve the problem of Hdf5 on Linux server without root: (Centos)
1. check if HDF5 is installed
`h5cc -showconfig`
2. download  HDF5 1.12 from [https://support.hdfgroup.org/ftp/HDF5/releases/](url)
3. install HDF5 on your local directory
4.  set environment path

**Comment by ychfan** [comment]
Good catch! Thanks!
